/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import controller.EnderecoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Endereco;


/**
 *
 * @author Claudinei
 */
public class ViewEndereco extends javax.swing.JFrame {
    
    ArrayList<Cliente> ListaCliente;

    
    public ViewEndereco() {
        initComponents();
        //Carrega os Clientes no Objetos cbxEnderecoCliente
        ClienteController clienteContrller = new ClienteController();
        
        for(Cliente cliente : clienteContrller.buscarClienteController()){
           cbxEnderecoCliente.addItem(cliente.getClienteNome());
        }

        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        btnEnderecoAdicionar = new javax.swing.JButton();
        btnEnderecoExcluir = new javax.swing.JButton();
        btnEnderecoAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtEndereco = new javax.swing.JTable();
        txtEnderecoCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtenderecoPesquisar = new javax.swing.JTextField();
        btnEnderecoPesquisar = new javax.swing.JButton();
        txtEnderecoDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        cbxEnderecoCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtEnderecoLogradouro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEnderecoNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        txtEnderecoUf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEnderecoCep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEnderecoComplemento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEnderecoBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEnderecoCidade = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmnSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro e Manutenção de Enderecos");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEnderecoAdicionar.setText("Salvar");
        btnEnderecoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecoAdicionarActionPerformed(evt);
            }
        });

        btnEnderecoExcluir.setText("Excluir");
        btnEnderecoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecoExcluirActionPerformed(evt);
            }
        });

        btnEnderecoAlterar.setText("Alterar");
        btnEnderecoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecoAlterarActionPerformed(evt);
            }
        });

        jtEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cliente", "Descricao", "Logradouro", "Numero", "Complemento", "CEP", "Bairro", "Cidade", "UF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEnderecoMouseClicked(evt);
            }
        });
        jtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtEnderecoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEnderecoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtEnderecoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtEndereco);

        txtEnderecoCodigo.setEditable(false);
        txtEnderecoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoCodigoActionPerformed(evt);
            }
        });

        jLabel4.setText("Codigo");

        txtenderecoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenderecoPesquisarActionPerformed(evt);
            }
        });

        btnEnderecoPesquisar.setText("Pesquisar");
        btnEnderecoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecoPesquisarActionPerformed(evt);
            }
        });

        txtEnderecoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoDescricaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Descricao");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        cbxEnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEnderecoClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Logradouro");

        txtEnderecoLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoLogradouroActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero");

        txtEnderecoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoNumeroActionPerformed(evt);
            }
        });

        jLabel5.setText("Cliente");

        jLabel7.setText("Cidade");

        txtEnderecoUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoUfActionPerformed(evt);
            }
        });

        jLabel8.setText("CEP");

        txtEnderecoCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoCepActionPerformed(evt);
            }
        });

        jLabel9.setText("Complemento");

        txtEnderecoComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoComplementoActionPerformed(evt);
            }
        });

        jLabel10.setText("Bairro");

        txtEnderecoBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoBairroActionPerformed(evt);
            }
        });

        jLabel11.setText("UF");

        txtEnderecoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoCidadeActionPerformed(evt);
            }
        });

        jMenu2.setText("Arquivo");

        jmnSair.setText("Sair");
        jmnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnSairActionPerformed(evt);
            }
        });
        jMenu2.add(jmnSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnderecoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxEnderecoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnderecoDescricao)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnEnderecoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEnderecoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEnderecoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtenderecoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEnderecoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtEnderecoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtEnderecoBairro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtEnderecoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(46, 46, 46))
                                    .addComponent(txtEnderecoUf)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtEnderecoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnderecoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtEnderecoComplemento)))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(txtEnderecoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtEnderecoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnderecoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnderecoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEnderecoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnderecoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnderecoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnderecoUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnderecoAdicionar)
                            .addComponent(btnEnderecoExcluir)
                            .addComponent(btnEnderecoAlterar))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtenderecoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnderecoPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnderecoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecoAdicionarActionPerformed

        Endereco endereco = new Endereco();
        EnderecoController enderecoController = new EnderecoController();

        endereco.setEnderecoDescricao(txtEnderecoDescricao.getText());
        endereco.setEnderecoLogradouro(txtEnderecoLogradouro.getText());
        endereco.setEnderecoNumero(txtEnderecoNumero.getText());
        endereco.setEnderecoComplemento(txtEnderecoComplemento.getText());
        endereco.setEnderecoCep(txtEnderecoCep.getText());
        endereco.setEnderecoBairro(txtEnderecoBairro.getText());
        endereco.setEnderecoCidade(txtEnderecoUf.getText());
        endereco.setEnderecoUf(txtEnderecoUf.getText());
     
        Cliente cliente = new Cliente(); 
        cliente.setClienteCodigo(cbxEnderecoCliente.getSelectedIndex()+1);
        endereco.setEnderecoCliente(cliente);
   

        enderecoController.inserirEnderecoController(endereco);

        txtEnderecoCodigo.setText("");
        txtEnderecoDescricao.setText("");
        txtEnderecoLogradouro.setText("");
        txtEnderecoNumero.setText("");
        txtEnderecoComplemento.setText("");
        txtEnderecoCep.setText("");
        txtEnderecoBairro.setText("");
        txtEnderecoCidade.setText("");
        txtEnderecoUf.setText("");

        atualizarTabela();
    }//GEN-LAST:event_btnEnderecoAdicionarActionPerformed

    public void atualizarTabela() {

        //limpa dados da DefaultTableModel
        DefaultTableModel modelo = (DefaultTableModel) jtEndereco.getModel();
        modelo.setNumRows(0);

        EnderecoController enderecoController = new EnderecoController();

        for (Endereco endereco : enderecoController.buscarEnderecoController()) {
            //DefaultTable
            modelo.addRow(new Object[]{
                endereco.getEnderecoCodigo(),
                endereco.getEnderecoCliente().getClienteNome(),
                endereco.getEnderecoDescricao(),
                endereco.getEnderecoLogradouro(),
                endereco.getEnderecoNumero(),
                endereco.getEnderecoComplemento(),
                endereco.getEnderecoCep(),
                endereco.getEnderecoBairro(),
                endereco.getEnderecoCidade(),
                endereco.getEnderecoUf()
            });

        }

    }
    
    
    private void btnEnderecoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecoExcluirActionPerformed
        //A6
        if (jtEndereco.getSelectedRow() != -1) { //verifica se está selecionada
            
            Endereco endereco = new Endereco();
            EnderecoController enderecoController = new EnderecoController();
            
            endereco.setEnderecoCodigo((int)jtEndereco.getValueAt(jtEndereco.getSelectedRow(), 0));
            
            enderecoController.excluirEnderecoController(endereco);
           
            txtEnderecoCodigo.setText("");
            txtEnderecoDescricao.setText("");
            txtEnderecoLogradouro.setText("");
            txtEnderecoNumero.setText("");
            txtEnderecoComplemento.setText("");
            txtEnderecoCep.setText("");
            txtEnderecoBairro.setText("");
            txtEnderecoCidade.setText("");
            txtEnderecoUf.setText("");
            
            //Atualiza tabela (grid)
            atualizarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um endereco para excluir");
        }
    }//GEN-LAST:event_btnEnderecoExcluirActionPerformed

    private void btnEnderecoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecoAlterarActionPerformed

        if (jtEndereco.getSelectedRow() != -1) {
            Endereco endereco = new Endereco();
            EnderecoController enderecoController = new EnderecoController();
            
            endereco.setEnderecoDescricao(txtEnderecoDescricao.getText());
            endereco.setEnderecoLogradouro(txtEnderecoLogradouro.getText());
            endereco.setEnderecoNumero(txtEnderecoNumero.getText());
            endereco.setEnderecoComplemento(txtEnderecoComplemento.getText());
            endereco.setEnderecoCep(txtEnderecoCep.getText());
            endereco.setEnderecoBairro(txtEnderecoBairro.getText());
            endereco.setEnderecoCidade(txtEnderecoUf.getText());
            endereco.setEnderecoUf(txtEnderecoUf.getText());
            
            Cliente cliente = new Cliente(); 
            cliente.setClienteCodigo(cbxEnderecoCliente.getSelectedIndex()+1);
            endereco.setEnderecoCliente(cliente);
        
            endereco.setEnderecoCodigo((int) jtEndereco.getValueAt(jtEndereco.getSelectedRow(), 0));
            
            enderecoController.atualizarEnderecoController(endereco);
            
            txtEnderecoCodigo.setText("");
            txtEnderecoDescricao.setText("");
            txtEnderecoLogradouro.setText("");
            txtEnderecoNumero.setText("");
            txtEnderecoComplemento.setText("");
            txtEnderecoCep.setText("");
            txtEnderecoBairro.setText("");
            txtEnderecoCidade.setText("");
            txtEnderecoUf.setText("");
            
            atualizarTabela();
        }

    }//GEN-LAST:event_btnEnderecoAlterarActionPerformed

    public void pesquisarEndereco(String enderecoDescricao) {

        //limpa dados da DefaultTableModel
        DefaultTableModel modelo = (DefaultTableModel) jtEndereco.getModel();
        modelo.setNumRows(0);

        EnderecoController enderecoController = new EnderecoController();

        for (Endereco endereco : enderecoController.buscarEnderecoController(enderecoDescricao)) {

            //DefaultTable
            modelo.addRow(new Object[]{
                endereco.getEnderecoCodigo(),
                endereco.getEnderecoCliente().getClienteNome(),
                endereco.getEnderecoDescricao(),
                endereco.getEnderecoLogradouro(),
                endereco.getEnderecoNumero(),
                endereco.getEnderecoComplemento(),
                endereco.getEnderecoCep(),
                endereco.getEnderecoBairro(),
                endereco.getEnderecoCidade(),
                endereco.getEnderecoUf()
            });

        }

    }


    private void txtEnderecoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoCodigoActionPerformed

    private void txtenderecoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenderecoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenderecoPesquisarActionPerformed

    private void btnEnderecoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecoPesquisarActionPerformed

        pesquisarEndereco(txtenderecoPesquisar.getText());

    }//GEN-LAST:event_btnEnderecoPesquisarActionPerformed

    private void txtEnderecoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoDescricaoActionPerformed

    private void jtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEnderecoKeyReleased
        if (jtEndereco.getSelectedRow() != -1) {
            txtEnderecoCodigo.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 0).toString());
            
            cbxEnderecoCliente.setSelectedItem(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 1).toString());
            
            txtEnderecoDescricao.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 2).toString());
            
            txtEnderecoLogradouro.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 3).toString());
            
            txtEnderecoNumero.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 4).toString());
            
            txtEnderecoComplemento.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 5).toString());
            
            txtEnderecoCep.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 6).toString());
            
            txtEnderecoBairro.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 7).toString());
            
            txtEnderecoCidade.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 8).toString());
            
            txtEnderecoUf.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 9).toString());  
        }
    }//GEN-LAST:event_jtEnderecoKeyReleased

    private void jtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEnderecoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEnderecoKeyPressed

    private void jtEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEnderecoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEnderecoKeyTyped

    private void jtEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEnderecoMouseClicked
        if (jtEndereco.getSelectedRow() != -1) {
           
            txtEnderecoCodigo.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 0).toString());
            
            cbxEnderecoCliente.setSelectedItem(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 1).toString());
            
            txtEnderecoDescricao.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 2).toString());
            
            txtEnderecoLogradouro.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 3).toString());
            
            txtEnderecoNumero.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 4).toString());
            
            txtEnderecoComplemento.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 5).toString());
            
            txtEnderecoCep.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 6).toString());
            
            txtEnderecoBairro.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 7).toString());
            
            txtEnderecoCidade.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 8).toString());
            
            txtEnderecoUf.setText(jtEndereco.getValueAt(
                    jtEndereco.getSelectedRow(), 9).toString());  
         }
    }//GEN-LAST:event_jtEnderecoMouseClicked

    private void jmnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnSairActionPerformed

        this.dispose(); // fecha esta tela

    }//GEN-LAST:event_jmnSairActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose(); // fecha esta tela
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtEnderecoLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoLogradouroActionPerformed

    private void txtEnderecoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoNumeroActionPerformed

    private void cbxEnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEnderecoClienteActionPerformed

    private void txtEnderecoUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoUfActionPerformed

    private void txtEnderecoCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoCepActionPerformed

    private void txtEnderecoComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoComplementoActionPerformed

    private void txtEnderecoBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoBairroActionPerformed

    private void txtEnderecoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnderecoAdicionar;
    private javax.swing.JButton btnEnderecoAlterar;
    private javax.swing.JButton btnEnderecoExcluir;
    private javax.swing.JButton btnEnderecoPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxEnderecoCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jmnSair;
    private javax.swing.JTable jtEndereco;
    private javax.swing.JTextField txtEnderecoBairro;
    private javax.swing.JTextField txtEnderecoCep;
    private javax.swing.JTextField txtEnderecoCidade;
    private javax.swing.JTextField txtEnderecoCodigo;
    private javax.swing.JTextField txtEnderecoComplemento;
    private javax.swing.JTextField txtEnderecoDescricao;
    private javax.swing.JTextField txtEnderecoLogradouro;
    private javax.swing.JTextField txtEnderecoNumero;
    private javax.swing.JTextField txtEnderecoUf;
    private javax.swing.JTextField txtenderecoPesquisar;
    // End of variables declaration//GEN-END:variables
}
