/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CategoriaController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Categoria;

/**
 *
 * @author Claudinei
 */
public class ViewCategoria extends javax.swing.JFrame {

    /**
     * Creates new form ViewCategoria
     */
    public ViewCategoria() {
        initComponents();

        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        btnCategoriaAdicionar = new javax.swing.JButton();
        btnCategoriaExcluir = new javax.swing.JButton();
        btnCategoriaAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCategoria = new javax.swing.JTable();
        txtCategoriaCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCategoriaPesquisar = new javax.swing.JTextField();
        btnCategoriaPesquisar = new javax.swing.JButton();
        txtCategoriaDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmnSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro e Manutenção de Categoria");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCategoriaAdicionar.setText("Salvar");
        btnCategoriaAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaAdicionarActionPerformed(evt);
            }
        });

        btnCategoriaExcluir.setText("Excluir");
        btnCategoriaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaExcluirActionPerformed(evt);
            }
        });

        btnCategoriaAlterar.setText("Alterar");
        btnCategoriaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaAlterarActionPerformed(evt);
            }
        });

        jtCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descricao", "Abreviatura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCategoriaMouseClicked(evt);
            }
        });
        jtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCategoriaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCategoriaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCategoriaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jtCategoria);

        txtCategoriaCodigo.setEditable(false);
        txtCategoriaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaCodigoActionPerformed(evt);
            }
        });

        jLabel4.setText("Codigo");

        txtCategoriaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaPesquisarActionPerformed(evt);
            }
        });

        btnCategoriaPesquisar.setText("Pesquisar");
        btnCategoriaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaPesquisarActionPerformed(evt);
            }
        });

        txtCategoriaDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaDescricaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Descricao");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jMenu2.setText("Arquivo");

        jmnSair.setText("Sair");
        jmnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnSairActionPerformed(evt);
            }
        });
        jMenu2.add(jmnSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(89, 89, 89)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtCategoriaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(txtCategoriaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnCategoriaAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCategoriaExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCategoriaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtCategoriaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnCategoriaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCategoriaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCategoriaAdicionar)
                    .addComponent(btnCategoriaExcluir)
                    .addComponent(btnCategoriaAlterar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtCategoriaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCategoriaPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnSair))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoriaAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaAdicionarActionPerformed

        Categoria categoria = new Categoria();
        CategoriaController categoriaController = new CategoriaController();

        categoria.setCategoriaDescricao(txtCategoriaDescricao.getText());
        //inserir categoria no BD
        categoriaController.inserirCategoriaController(categoria);

        txtCategoriaCodigo.setText("");
        txtCategoriaDescricao.setText("");

        //Atualiza tabela (grid)
        atualizarTabela();
    }//GEN-LAST:event_btnCategoriaAdicionarActionPerformed

    public void atualizarTabela() {

        //limpa dados da DefaultTableModel
        DefaultTableModel modelo = (DefaultTableModel) jtCategoria.getModel();
        modelo.setNumRows(0);

        CategoriaController categoriaController = new CategoriaController();

        for (Categoria categoria : categoriaController.buscarCategoriasController()) {
            //DefaultTable
            modelo.addRow(new Object[]{
                categoria.getCategoriaCodigo(),
                categoria.getCategoriaDescricao()

            });

        }

    }
    private void btnCategoriaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaExcluirActionPerformed
        //A6
        if (jtCategoria.getSelectedRow() != -1) { //verifica se está selecionada
            Categoria categoria = new Categoria();
            CategoriaController categoriaController = new CategoriaController();
            //excluir categoria no BD
            categoria.setCategoriaCodigo((int) 
                    jtCategoria.getValueAt(jtCategoria.getSelectedRow(), 0));
            categoriaController.excluirCategoriaController(categoria);
            txtCategoriaCodigo.setText("");
            txtCategoriaDescricao.setText("");
            //Atualiza tabela (grid)
            atualizarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um categoria para excluir");
        }
    }//GEN-LAST:event_btnCategoriaExcluirActionPerformed

    private void btnCategoriaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaAlterarActionPerformed

        if (jtCategoria.getSelectedRow() != -1) {
            Categoria categoria = new Categoria();
            CategoriaController categoriaController = new CategoriaController();
            categoria.setCategoriaDescricao(txtCategoriaDescricao.getText());
            categoria.setCategoriaCodigo((int) jtCategoria.getValueAt(
                    jtCategoria.getSelectedRow(), 0));
            categoriaController.atualizarCategoriaController(categoria);
            txtCategoriaCodigo.setText("");
            txtCategoriaDescricao.setText("");
            atualizarTabela();
        }

    }//GEN-LAST:event_btnCategoriaAlterarActionPerformed

    public void pesquisarCategoria(String categoriaDescricao) {

        //limpa dados da DefaultTableModel
        DefaultTableModel modelo = (DefaultTableModel) jtCategoria.getModel();
        modelo.setNumRows(0);

        CategoriaController categoriaController = new CategoriaController();

        for (Categoria categoria : categoriaController.buscarCategoriasController(categoriaDescricao)) {

            //DefaultTable
            modelo.addRow(new Object[]{
                categoria.getCategoriaCodigo(),
                categoria.getCategoriaDescricao(),});

        }

    }


    private void txtCategoriaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaCodigoActionPerformed

    private void txtCategoriaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaPesquisarActionPerformed

    private void btnCategoriaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaPesquisarActionPerformed

        pesquisarCategoria(txtCategoriaPesquisar.getText());

    }//GEN-LAST:event_btnCategoriaPesquisarActionPerformed

    private void txtCategoriaDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaDescricaoActionPerformed

    private void jtCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCategoriaKeyReleased
        if (jtCategoria.getSelectedRow() != -1) {
            txtCategoriaCodigo.setText(jtCategoria.getValueAt(jtCategoria.getSelectedRow(), 0).toString());
            txtCategoriaDescricao.setText(jtCategoria.getValueAt(jtCategoria.getSelectedRow(), 1).toString());

        }
    }//GEN-LAST:event_jtCategoriaKeyReleased

    private void jtCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCategoriaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCategoriaKeyPressed

    private void jtCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCategoriaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCategoriaKeyTyped

    private void jtCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCategoriaMouseClicked
        if (jtCategoria.getSelectedRow() != -1) {
           
            txtCategoriaCodigo.setText(jtCategoria.getValueAt(
                    jtCategoria.getSelectedRow(), 0).toString());
            
            txtCategoriaDescricao.setText(jtCategoria.getValueAt(
                    jtCategoria.getSelectedRow(), 1).toString());

        }
    }//GEN-LAST:event_jtCategoriaMouseClicked

    private void jmnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnSairActionPerformed

        this.dispose(); // fecha esta tela

    }//GEN-LAST:event_jmnSairActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose(); // fecha esta tela
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoriaAdicionar;
    private javax.swing.JButton btnCategoriaAlterar;
    private javax.swing.JButton btnCategoriaExcluir;
    private javax.swing.JButton btnCategoriaPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jmnSair;
    private javax.swing.JTable jtCategoria;
    private javax.swing.JTextField txtCategoriaCodigo;
    private javax.swing.JTextField txtCategoriaDescricao;
    private javax.swing.JTextField txtCategoriaPesquisar;
    // End of variables declaration//GEN-END:variables
}
