/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;


/**
 *
 * @author Claudinei
 */
public class ViewCliente extends javax.swing.JFrame {
    
    ArrayList<Cliente> ListaCliente;

    
    public ViewCliente() {
        initComponents();

        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        btnClienteAdicionar = new javax.swing.JButton();
        btnClienteExcluir = new javax.swing.JButton();
        btnClienteAlterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCliente = new javax.swing.JTable();
        txtClienteCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClientePesquisar = new javax.swing.JTextField();
        btnEnderecoPesquisar = new javax.swing.JButton();
        txtClienteNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtClienteTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClienteCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();
        txtDtNascimento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtClienteEmail = new javax.swing.JTextField();
        txtClienteCpf = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmnSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro e Manutenção de Clientes");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnClienteAdicionar.setText("Salvar");
        btnClienteAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAdicionarActionPerformed(evt);
            }
        });

        btnClienteExcluir.setText("Excluir");
        btnClienteExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteExcluirActionPerformed(evt);
            }
        });

        btnClienteAlterar.setText("Alterar");
        btnClienteAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAlterarActionPerformed(evt);
            }
        });

        jtCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "CPF", "Telefone", "Celular", "E-mail", "Dt Nasc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClienteMouseClicked(evt);
            }
        });
        jtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtClienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtClienteKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtCliente);

        txtClienteCodigo.setEditable(false);
        txtClienteCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteCodigoActionPerformed(evt);
            }
        });

        jLabel4.setText("Codigo");

        txtClientePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientePesquisarActionPerformed(evt);
            }
        });

        btnEnderecoPesquisar.setText("Pesquisar");
        btnEnderecoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecoPesquisarActionPerformed(evt);
            }
        });

        txtClienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel2.setText("Telefone");

        txtClienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteTelefoneActionPerformed(evt);
            }
        });

        jLabel3.setText("Celular");

        txtClienteCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteCelularActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome");

        jLabel8.setText("Dt Nasc");

        txtDtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtNascimentoActionPerformed(evt);
            }
        });

        jLabel9.setText("E-mail");

        txtClienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteEmailActionPerformed(evt);
            }
        });

        txtClienteCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteCpfActionPerformed(evt);
            }
        });

        jMenu2.setText("Arquivo");

        jmnSair.setText("Sair");
        jmnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnSairActionPerformed(evt);
            }
        });
        jMenu2.add(jmnSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtClienteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(55, 55, 55))
                                    .addComponent(txtDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClienteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtClienteNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtClientePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnderecoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClienteAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClienteExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClienteAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtClienteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClienteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteAdicionar)
                    .addComponent(btnClienteExcluir)
                    .addComponent(btnClienteAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClientePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnderecoPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAdicionarActionPerformed

        Cliente cliente = new Cliente();
        ClienteController clienteController = new ClienteController();

        cliente.setClienteNome(txtClienteNome.getText());
        cliente.setClienteCpf(txtClienteCpf.getText());
        cliente.setClienteTelefone(txtClienteTelefone.getText());
        cliente.setClienteCelular(txtClienteCelular.getText());
        cliente.setClienteEmail(txtClienteEmail.getText());
        cliente.setClienteDtNascimento(txtDtNascimento.getText());
  

        clienteController.inserirClienteController(cliente);

        txtClienteCodigo.setText("");
        txtClienteNome.setText("");
        txtClienteCpf.setText("");
        txtClienteTelefone.setText("");
        txtClienteCelular.setText("");
        txtClienteEmail.setText("");
        txtDtNascimento.setText("");

        atualizarTabela();
    }//GEN-LAST:event_btnClienteAdicionarActionPerformed

    public void atualizarTabela() {

        //limpa dados da DefaultTableModel
        DefaultTableModel modelo = (DefaultTableModel) jtCliente.getModel();
        modelo.setNumRows(0);

        ClienteController clienteController = new ClienteController();

        for (Cliente cliente : clienteController.buscarClienteController()) {
            //DefaultTable
            modelo.addRow(new Object[]{
                cliente.getClienteCodigo(),
                cliente.getClienteNome(),
                cliente.getClienteCpf(),
                cliente.getClienteTelefone(),
                cliente.getClienteCelular(),
                cliente.getClienteEmail(),
                cliente.getClienteDtNascimento()
            });

        }

    }
    
    
    private void btnClienteExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteExcluirActionPerformed
        //A6
        if (jtCliente.getSelectedRow() != -1) { //verifica se está selecionada
            
            Cliente cliente = new Cliente();
            ClienteController clienteController = new ClienteController();
            
            cliente.setClienteCodigo((int)jtCliente.getValueAt(jtCliente.getSelectedRow(), 0));
            
            clienteController.excluirClienteController(cliente);
           
            txtClienteCodigo.setText("");
            txtClienteNome.setText("");
            txtClienteCpf.setText("");
            txtClienteTelefone.setText("");
            txtClienteCelular.setText("");
            txtClienteEmail.setText("");
            txtDtNascimento.setText("");
            
            //Atualiza tabela (grid)
            atualizarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um endereco para excluir");
        }
    }//GEN-LAST:event_btnClienteExcluirActionPerformed

    private void btnClienteAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAlterarActionPerformed

        if (jtCliente.getSelectedRow() != -1) {
            
            Cliente cliente = new Cliente();
            ClienteController clienteController = new ClienteController();
            
            cliente.setClienteNome(txtClienteNome.getText());
            cliente.setClienteCpf(txtClienteCpf.getText());
            cliente.setClienteTelefone(txtClienteTelefone.getText());
            cliente.setClienteCelular(txtClienteCelular.getText());
            cliente.setClienteEmail(txtClienteEmail.getText());
            cliente.setClienteDtNascimento(txtDtNascimento.getText());
        
            cliente.setClienteCodigo((int)jtCliente.getValueAt(jtCliente.getSelectedRow(), 0));
            
            clienteController.atualizarlienteController(cliente);
            
            txtClienteCodigo.setText("");
            txtClienteNome.setText("");
            txtClienteCpf.setText("");
            txtClienteTelefone.setText("");
            txtClienteCelular.setText("");
            txtClienteEmail.setText("");
            txtDtNascimento.setText("");
            
            atualizarTabela();
        }

    }//GEN-LAST:event_btnClienteAlterarActionPerformed

    public void pesquisarCliente(String clienteNome) {

        //limpa dados da DefaultTableModel
        DefaultTableModel modelo = (DefaultTableModel) jtCliente.getModel();
        modelo.setNumRows(0);

        ClienteController clienteController = new ClienteController();

        for (Cliente cliente : clienteController.buscarClienteController(clienteNome)) {

            //DefaultTable
            modelo.addRow(new Object[]{
                cliente.getClienteCodigo(),
                cliente.getClienteNome(),
                cliente.getClienteCpf(),
                cliente.getClienteTelefone(),
                cliente.getClienteCelular(),
                cliente.getClienteEmail(),
                cliente.getClienteDtNascimento()
            });

        }

    }


    private void txtClienteCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteCodigoActionPerformed

    private void txtClientePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientePesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientePesquisarActionPerformed

    private void btnEnderecoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecoPesquisarActionPerformed

        pesquisarCliente(txtClientePesquisar.getText());

    }//GEN-LAST:event_btnEnderecoPesquisarActionPerformed

    private void txtClienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteNomeActionPerformed

    private void jtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtClienteKeyReleased
        if (jtCliente.getSelectedRow() != -1) {
            txtClienteCodigo.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 0).toString());
            
            txtClienteNome.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 1).toString());
            
             txtClienteCpf.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 2).toString());
            
            txtClienteTelefone.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 3).toString());
            
            txtClienteCelular.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 4).toString());
            
            txtClienteEmail.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 5).toString());
            
            txtDtNascimento.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 6).toString());
        }
    }//GEN-LAST:event_jtClienteKeyReleased

    private void jtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtClienteKeyPressed

    private void jtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtClienteKeyTyped

    private void jtClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClienteMouseClicked
        if (jtCliente.getSelectedRow() != -1) {
           
            txtClienteCodigo.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 0).toString());
            
            txtClienteNome.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 1).toString());
            
             txtClienteCpf.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 2).toString());
            
            txtClienteTelefone.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 3).toString());
            
            txtClienteCelular.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 4).toString());
            
            txtClienteEmail.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 5).toString());
            
            txtDtNascimento.setText(jtCliente.getValueAt(
                    jtCliente.getSelectedRow(), 6).toString());
         }
    }//GEN-LAST:event_jtClienteMouseClicked

    private void jmnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnSairActionPerformed

        this.dispose(); // fecha esta tela

    }//GEN-LAST:event_jmnSairActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose(); // fecha esta tela
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtClienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteTelefoneActionPerformed

    private void txtClienteCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteCelularActionPerformed

    private void txtDtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtNascimentoActionPerformed

    private void txtClienteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteEmailActionPerformed

    private void txtClienteCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteAdicionar;
    private javax.swing.JButton btnClienteAlterar;
    private javax.swing.JButton btnClienteExcluir;
    private javax.swing.JButton btnEnderecoPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jmnSair;
    private javax.swing.JTable jtCliente;
    private javax.swing.JTextField txtClienteCelular;
    private javax.swing.JTextField txtClienteCodigo;
    private javax.swing.JTextField txtClienteCpf;
    private javax.swing.JTextField txtClienteEmail;
    private javax.swing.JTextField txtClienteNome;
    private javax.swing.JTextField txtClientePesquisar;
    private javax.swing.JTextField txtClienteTelefone;
    private javax.swing.JTextField txtDtNascimento;
    // End of variables declaration//GEN-END:variables
}
